### ISSUE TITLE
Screenshots give error when using landscape orientation

### ISSUE THREAD

**Issue by richardhendricksen** [DevExpress/testcafe-browser-provider-browserstack#148] opened 2021-03-04 09:27 UTC
When testing against devices e.g. (`browserstack:iPad Air 2019@13`) you can use the `deviceOrientation` capability to use the device in landscape mode.
When passing this capability using the configuration file the test fails when it takes a screenshot with the following error:
```
Was unable to take a screenshot due to an error.

  Error: Unable to locate the page area in the browser window screenshot at /<local_path>/2021-03-04_08-45-45/test-1/Safari_13.1.1_macOS_10.15.4/errors/1.png, because the page area mark with ID
  2648572802 is not found in the screenshot.
```

The issue is that when using the landscape orientation Browserstack rotates the screenshots 90 degrees:
![image](https://user-images.githubusercontent.com/15088741/109929255-8d3ebd00-7cc6-11eb-90bf-bfb1cec18d45.png)
Testcafe expects the screenshot to be in the normal orientation so it can parse the page area mark. So a simple rotate should fix this issue. I will create a PR adding support for the landscape orientation.

**Comment by richardhendricksen** [comment] 2021-03-04 11:46
Seems not all devices are created equal on browserstack, i did somet testing and Android tablets in landscape mode do seem to return a normal screenshot. I'll do some extra testing to see if the 90 degrees only applies to Apple/iPads.

**Comment by richardhendricksen** [comment] 2021-03-04 11:59
after some testing it seems the screenshot rotation only applies to iOS devices. Updated PR to only rotate back when it's an iOS device

**Comment by wentwrong** [comment] 2021-03-08 11:24
Thank you for your effort. I reproduced the issue. When some devices are being used, BrowserStack captures the screenshot rotated 90 degrees. This leads to the error when we try to process it. 

But I found that when I use the `browserstack:iPhone XS@14` device, BrowserStack creates an unrotated screenshot:

<img src="https://user-images.githubusercontent.com/26363017/110314303-b938a600-8018-11eb-94f3-2fd5b9704639.PNG" alt="Screenshot in the BrowserStack dashboard" width="450" height="200">

In this case, if we rotate the screenshot on our end, it can't be processed either:

<img src="https://user-images.githubusercontent.com/26363017/110314000-5515e200-8018-11eb-848d-6a69ddf1dc98.png  " alt="Processed screenshot" width="150" height="300">

So, checking that the testing device's OS is "iOS" and in the landscape mode doesn't cover all cases.

Also, did you report the issue with unnecessary rotation of the screenshot to the BrowserStack team? This might be better resolved on their side. What do you think?

**Comment by richardhendricksen** [comment] 2021-03-08 11:55
Thanks for the response, seems the behaviour is even more specific than I thought. I'll try to see if I can pinpoint which devices the rotation applies to.
Good idea about reporting the issue to the Browserstack team, I will do so at once, if I get any replies i'll add those here.

**Comment by richardhendricksen** [comment] 2021-03-08 12:50
Already got a response from the Browserstack team:
```
I would like to share that, the behavior you reported wherein the screenshots did not honor the landscape orientation you configured when running Automate tests on iOS devices. 

We checked this internally with our engineering team and would want to share that our implementation of the screenshots and video logging functionality differs on Android and iOS devices. By default, the orientation capability is honored on Android devices and the screenshots and video are subsequently generated based on the capability the user sets. However, the above does not hold true for iOS devices. Thus, you witness the reported behavior. 

With that being said, our engineering team has decided to take this is as an improvement in the product and revamp the screenshots and video logging functionality for iOS devices to ensure that the behavior is consistent across our infrastructure. However, this would require a significant amount of time, and thus, we will be unable to share an ETA at the moment. 

Rest assured, we will be proactively notifying you of the updates/developments on priority. 
```

So they will fix it, but no ETA yet.

**Comment by wentwrong** [comment] 2021-03-09 08:05
Thank you for the quick report to the BrowserStack team and for sharing their response. As I said before, I think that it's better to resolve the issue on the BrowserStack side. Since they are already aware of the inconsistent screenshot capturing in landscape mode and you have a workaround for your project, I think we should close it for now.

**Closed by wentwrong** 2021-03-09 08:05 UTC
Labels: STATE: Need response
