### ISSUE TITLE
Does not work for Edge or IE

### ISSUE THREAD

**Issue by owen-m1** [DevExpress/testcafe-browser-provider-browserstack#81] opened 2019-07-06 23:19 UTC
If I run my tests using any version of Edge or IE (eg. `browserstack:edge@16.0:Windows 10`, `browserstack:ie@11.0:Windows 10`, etc.), the test will never begin and it will hang for minutes until it eventually will give the error:
`ERROR Unable to establish one or more of the specified browser connections. This can be caused by network issues or remote device failure.`

If I watch the live streaming of the Browserstack emulator, I can see it is just stuck on the testcafe loading screen, but the browser has indeed started.

Similar issue: https://github.com/DevExpress/testcafe/issues/2480

**Comment by owen-m1** [comment] 2019-07-07 02:00
Since this issue has been reported in other testing frameworks, and the issue seems to be resolved just by running the test at a different time (though my results are inconsistent), I am going to guess this is most likely an issue with Browserstack's emulators.

**Comment by owen-m1** [comment] 2019-07-08 12:50
It seems that the error I am getting is now a validation error:
`StatusCodeError: 403 - {"message":"Validation Failed","errors":[{"field":"id","code":"invalid"}]}`

It happens with CircleCI as you can see here: https://circleci.com/gh/SortableJS/Sortable/12

Take a look at [this test](https://circleci.com/gh/SortableJS/Sortable/11) compared to [this test](https://circleci.com/gh/SortableJS/Sortable/12). In the commit, I only removed an unused variable, but the second test fails with a validation error while the first one passed.

**Comment by aleks-pro** [comment] 2019-07-08 19:55
Hello @owen-m1 ,

Thank you for the provided information but it's insufficient to determine the cause of the problem you encounter. The validation error you are facing is not a TestCafe error and we need to check in what way it is related to the TestCafe code.
If it is possible, provide us with the project running on the Circle Ci server so we will be able to examine the issue on our side.

**Comment by owen-m1** [comment] 2019-07-08 21:04
@aleks-pro This is the branch that I have the tests on: https://github.com/SortableJS/Sortable/tree/testcafe-tests

Here is the CircleCI test with the failure: https://circleci.com/gh/SortableJS/Sortable/12
Here you can see it passes when I remove IE and Edge: https://circleci.com/gh/SortableJS/Sortable/13

**Comment by LavrovArtem** [comment] 2019-07-09 15:06
https://circleci.com/gh/SortableJS/Sortable/15

Judging by the build, your tests work in IE/Edge now, so we are closing the ticket. However, we did not find out the cause of this behavior. Could you explain what you had to change in order to achieve this?

**Closed by LavrovArtem** 2019-07-09 15:06 UTC
Labels: STATE: Need response

**Comment by owen-m1** [comment] 2019-07-09 15:10
@LavrovArtem It really seems to be an issue on Browserstack's end. It even started happening on other browsers such as MacOS Safari. I contacted them about it, but it looks like I am going to have to switch to Saucelabs as of right now, since I have tested with them and had no problems 👌. Thanks for your help.

**Comment by AndreyBelym** [comment] 2019-09-16 09:17
@ckzgraphics, the file you mentioned is a test that checks the error message. This is the correct reference to the code that throws this error: [src/runner/browser-set.js#L59](https://github.com/DevExpress/testcafe/blob/master/src/runner/browser-set.js#L59).

It means that the TestCafe server didn't receive any request from the browser. Unfortunately, it can be caused by a number of reasons and we have no additional debug information. Since there is no connection between the browser and the TestCafe server, you can only try to open DevTools in the browser, open the Network tab and export a HAR report.
