### ISSUE TITLE
ci:  checking out wrong branch?

### ISSUE THREAD

**Issue by kukhariev** [DevExpress/testcafe-browser-provider-browserstack#181] opened 2022-08-29 07:15 UTC
It seems that now the default `master` build is always tested, not the PR build.
![image](https://user-images.githubusercontent.com/13515406/187142162-c927e690-7268-4352-9640-8e18a52c5526.png)

**Comment by felis2803** [comment] 2022-09-01 10:26
It looks like it was a one-time issue at [#177](https://github.com/DevExpress/testcafe-browser-provider-browserstack/pull/177).
It was not reproduced in your PR [#180](https://github.com/DevExpress/testcafe-browser-provider-browserstack/pull/180).
Have you seen this odd behavior anywhere else?

**Comment by kukhariev** [comment] 2022-09-01 12:42
@felis2803 , 
#180 PR affected too. But it's okay if I use push(--force)
Also #175, #179

**Comment by felis2803** [comment] 2022-09-02 09:24
You're right. I ran some tests in #182 and #183 and found that this behavior happens quite often. I intentionally messed up the test in #182, but it was passed.

Thank you for bringing this up.

**Comment by AndreyBelym** [comment] 2022-09-13 13:48
The bug happened when GitHub couldn't create a merge commit between the PR branch and the base branch fast enough. I refactored the code that queries the merge commit SHA, so our build system should wait until the merge commit is created. It seems that the issue is fixed now.

**Closed by AndreyBelym** 2022-09-13 13:48 UTC
Labels: bug
