### ISSUE TITLE
OS X tests not connecting

### ISSUE THREAD

**Issue by liwanma** [DevExpress/testcafe-browser-provider-browserstack#207] opened 2023-08-30 05:20 UTC
I have a test suite that targets the latest versions of firefox (windows), edge (windows), and safari (OS X). Until August 21, our tests were running fine on all three browsers.  Now, on safari, the tests get stuck at `Safari Can't Open the Page`.  I've tried targeting Safari 16.5 on Ventura but see the same issue (where they previously used to pass).  I then tried running firefox on OSX (Sonoma and Ventura), and they also failed (`The connection has timed out`).

Testing on windows is still working.  Everything runs fine locally.

**Comment by dgurin-squareup** [comment] 2023-08-30 17:34
I'm seeing the same issue, as of the same date

**Comment by aleks-pro** [comment] 2023-09-18 10:52
Hello @liwanma , @dgurin-squareup ,

I tried to reproduce the issue on Mac OS Ventura and Safari 16.5 using `testcafe` (version 3.3.0),`testcafe-browser-provider-browserstack` (version `1.15.1`), and Node JS (version 20.1.0), but everything works fine for me. Could you please specify versions of `testcafe`,`testcafe-browser-provider-browserstack`, and Node JS you are using?

**Comment by dgurin-squareup** [comment] 2023-09-19 00:50
@aleks-pro The issue is reproduced with the same version of `testcafe@3.3.0`, and `testcafe-browser-provider-browserstack@1.15.1`, and Node v18

**Comment by liwanma** [comment] 2023-09-19 01:14
@aleks-pro
`testcafe@3.3.0`
`testcafe-browser-provider-browserstack@1.15.1`
Node v16

**Comment by aleks-pro** [comment] 2023-09-25 12:21
I did not manage to reproduce the issue on NodeJS versions 16.17.0 and 18.4.0 using the following project: https://github.com/DevExpress/testcafe-browser-provider-browserstack/files/12674653/i270.zip. Please try to reproduce the issue with this project (run the `npm ci` command first than start tests with the `npx testcafe "browserstack:safari@16.5:OS X Ventura"` command) and share your results.

**Comment by liwanma** [comment] 2023-09-26 02:08
@aleks-pro
Your example project is working as you described.  Strange enough, my tests have also started working again.  Maybe it was an issue on the browserstack side?

**Comment by aleks-pro** [comment] 2023-09-27 10:32
Hello,

 > Maybe it was an issue on the browserstack side?

 Possibly, but I cannot say for sure. I am happy to hear that this behavior doesn't reproduce anymore. I will close this issue. If you encounter similar behavior in the future, please create a new issue with a reproducible example.

**Closed by aleks-pro** 2023-09-27 10:32 UTC
Labels: STATE: Need response
