### ISSUE TITLE
Allow configuration of capabilities.name 

### ISSUE THREAD

**Issue by chheller** [DevExpress/testcafe-browser-provider-browserstack#49] opened 2018-08-16 18:51 UTC
This is an enhancement and an extension of issue #31 which was closed without a proper resolution.

When running tests on Browserstack, especially with concurrency, having each test run given a random ID is not helpful for identifying the specific test files or fixtures which have failed. Being able to set the Project Name isn't helpful at all in this capacity, as it's a much higher level of organization, as is the Build Name (mistakenly referred to as BROWSERSTACK_BUILD_ID, the Build ID is a separate field in a Browserstack build than the name) which only allows for grouping of test runs into a similar collection. This issue becomes more noticeable when running with concurrency, as each fixture gets its own unique session within the Browserstack build, however the URL reported by the CLI is only the latest session rather than a proper list of sessions.

For instance, running testcafe 4 times in sequence to cover 4 browsers yields 
![screen shot 2018-08-16 at 1 22 23 pm](https://user-images.githubusercontent.com/2985885/44227207-af4bb080-a157-11e8-8e75-72b2a8818442.png)
![screen shot 2018-08-16 at 1 24 40 pm](https://user-images.githubusercontent.com/2985885/44227247-c2f71700-a157-11e8-94bb-fd90bc46e003.png)

Here, each run is only really identifiable by the Browser/OS combination as each session's name is random. The URL correctly links back to the corresponding session.

However, when running with a concurrency of 2 to take advantage of our Browserstack plan
![screen shot 2018-08-16 at 1 32 50 pm](https://user-images.githubusercontent.com/2985885/44227731-01410600-a159-11e8-8e8c-f4987bc2a3aa.png)
![screen shot 2018-08-16 at 1 34 09 pm](https://user-images.githubusercontent.com/2985885/44227770-1a49b700-a159-11e8-8f98-0eadd6978176.png)

It's worth noting that it becomes significantly more difficult to identify the fixture ran in each session from Browserstack as now the URL reported by CLI only references the _last_ session, rather than both of the sessions which were created.

 Additionally, There appears to be some sort of dependency between tests run concurrently, as the run time for the two parallel sessions are both approximately as long as the single session which runs both fixtures sequentially, further explanation in #48

testcafe `0.21.0`
node: `8.9.1`
testcafe-browser-provider-browserstack `1.5.0`
Browsers:
Firefox `61.0`
Chrome `68.0`
Edge `17.0`
Run on `Mac OS X High Sierra 10.13.6`

**Comment by sparda2** [comment] 2019-09-20 17:13
So this is still unresolved to the date? did you figure any work arounds for this?

**Comment by AlexKamaev** [comment] 2019-09-23 09:42
Not yet, the issue is still in our plans, but we cannot give you any estimated time frames.

**Comment by mansn** [comment] 2020-01-23 08:56
This issue can be closed, right? Since #85 is merged.

**Comment by AndreyBelym** [comment] 2020-01-23 11:13
Thank you, yes, it's merged and available in `v1.10.0`.

**Closed by AndreyBelym** 2020-01-23 11:13 UTC
Labels: STATE: Need response, enhancement
