### ISSUE TITLE
Race condition in takeScreenshot, causing it to not-crop sometimes

### ISSUE THREAD

**Issue by jankeesvanandel** [DevExpress/testcafe-browser-provider-browserstack#143] opened 2020-12-11 16:52 UTC
Hi,

In our company we're happily using TestCafe, using BrowserStack. We've built a small framework around it, to take screenshots and compare them with baseline screenshots. We use the takeElementScreenshot for this to only compare the relevant portions.

To do so, we read the screenshot that testcafe generated and we do a compare. If the compare fails, the test fails. So far so good.

But once in a while we run into an error where the screenshots don't match, because the screenshot is not cropped, but the full page. At first it looked like a bug on our side, but after digging deeper, I found out that the cause is in the Capturer class in Testcafe. I've added some logging to the catch clause in: `Capturer._isScreenshotCaptured` and I've added a small retry mechanism.

I saw quite a bit of these errors: `Error: ENOENT: no such file or directory, stat '/path/to/Deeplink to a page_Chrome_Windows_1.png'`. Usually it happened once and then with the retry it worked, but sometimes it needed another retry.

So I started diving into the takeScreenshot code in the browserstack provider and I found the following code:
https://github.com/DevExpress/testcafe-browser-provider-browserstack/blob/0bc262ba01efdec43fc3e69e470267b4bae5a695/src/backends/automate.js#L184

It's awaiting a synchronous method. I would expect an error here, since `write` doesn't return a Promise. I don't know why the JS runtime doesnt't, but after changing the line to `await image.writeAsync(screenshotPath);` it worked perfectly.

Do you agree with this conclusion? And if yes, could you fix this please? It's making our tests very unstable.

Thanks!

**Comment by AlexKamaev** [comment] 2020-12-14 08:29
@jankeesvanandel
Thank you for pointing this out to us. I took a look at the `jimp` module. It looks like that you are right and that's correct to use the `writeAsync` method. However, we need time to check it in detail.
We would also appreciate it if you can share an example that demonstrates the issue to be sure that the cause of it lies in that method.

**Comment by jankeesvanandel** [comment] 2020-12-14 11:04
Hi @AlexKamaev ,

I've created a small test app to illustrate the issue. It's a bit of a copy-paste mess, but I think it can be useful to reproduce the issue. I also committed the screenshots, so you can see the problem. https://github.com/jankeesvanandel/testcafe-screenshot-example

We run with quarantineMode=true, so in the `e2e/screenshots/tests` directory you'll find screenshots from three runs. Run 1 and 2 were correct, but the 3rd run went wrong.

You can run the test suite yourself using `export BROWSERSTACK_USERNAME="your-bs-username"; export BROWSERSTACK_ACCESS_KEY="your-bs-access-key"; yarn e2e:bs`

I can be of any help, just let me know. 😄

**Comment by AlexKamaev** [comment] 2020-12-15 08:41
@jankeesvanandel
I was not able to reproduce the issue in your example. I ran the tests multiple times, but everything works as expected. I believe that using `write` is incorrect, but I'm not sure that it is the real cause of the issue. However, I still think that we need to use the correct method. At the moment, we are working on other issues, so I would ask you to create a PR with the fix.
In addition, would you please modify your example so that it reproduces the issue more stably if it's possible.

**Comment by jankeesvanandel** [comment] 2020-12-15 09:23
I'm not sure how to make it fully reproducible, since I expect it also depends a lot on the hardware and OS it's running on. For example, on our  (Linux) CI servers, it's more stable than on my high end Macbook. I've tried to use high res screenshots to make it "slower" on the file writing part, but it's not guaranteed.

I've run many times with a locally applied fix now and it's perfectly stable with the fix (the writeAsync method) and it often breaks without the fix.

I'll see if I can find some command line settings for node to increase the fail rate.

**Comment by AlexKamaev** [comment] 2020-12-16 07:30
@jankeesvanandel, I perfectly understand what you mean. Thank you for your cooperation. Like I said, I admit we have a mistake in our code base, so your PR will be highly welcome.

**Comment by jankeesvanandel** [comment] 2020-12-17 09:43
PR created. See: https://github.com/DevExpress/testcafe-browser-provider-browserstack/pull/144

**Comment by AlexKamaev** [comment] 2020-12-18 08:19
@jankeesvanandel
I merged your PR and the [1.13.2-alpha.1](https://www.npmjs.com/package/testcafe-browser-provider-browserstack/v/1.13.2-alpha.1) version in npm. Please check this version with your test suite. If your tests pass, we'll publish the official 1.13.2 release.

**Closed by AlexKamaev** 2020-12-18 08:19 UTC
Labels: STATE: Need response, bug

**Comment by jankeesvanandel** [comment] 2020-12-18 14:04
Oh yes, it works like a charm. Ran it many times and not even a single unstable test!
Looking forward for the official release.
Thanks @AlexKamaev for the quick help!
